### ISSUE TITLE
pickle.load error

### ISSUE THREAD

**Issue by hust-nj** [graphdeeplearning/benchmarking-gnns#10]
Hi, I encountered an error when I loaded the MNIST.pkl and CIFAR10.pkl
```bash

<stdout>:cuda available with GPU: Tesla P100-PCIE-16GB
<stdout>:[I] Loading dataset CIFAR10...
<stderr>:Traceback (most recent call last):
<stderr>:  File "tools/train_superpixels_graph_classification.py", line 444, in <module>
<stderr>:    main() 
<stderr>:  File "tools/train_superpixels_graph_classification.py", line 325, in main
<stderr>:    dataset = LoadData(DATASET_NAME, data_dir=args.dataDir)
<stderr>:  File "/var/storage/shared/nextmsra/sys/jobs/application_1583577754071_28152/gnn/data/data.py", line 18, in LoadData
<stderr>:    return SuperPixDataset(DATASET_NAME, data_dir)
<stderr>:  File "/var/storage/shared/nextmsra/sys/jobs/application_1583577754071_28152/gnn/data/superpixels.py", line 271, in __init__
<stderr>:    f = pickle.load(f)
<stderr>:  File "/tmp/cache/python/lib/python3.7/site-packages/dgl/graph_index.py", line 53, in __setstate__
<stderr>:    num_nodes, readonly, src, dst = state
<stderr>:ValueError: too many values to unpack (expected 4)
```
Here is my environment.
cuda version :10.0
pytorch version : pytorch 1.4 with cudatoolkit 10.0
dgl version:  v0.4.3 

I wonder if the new dgl version causes the inconsistency.
Because I can run well when dgl is v0.4.2., but now I don't find how to downgrade my dgl to v0.4.2 explicitly.
Thanks for solving this :)
Or can you publish your code of how to generate the dgl graph from CIFAR and MNIST dataset?
Thank you

**Comment by hust-nj** [comment]
What's more, I changed your code slightly for custom.
And when I explicitly using pickle.load in python interactive shell, I encountered the same error

> ValueError: too many values to unpack (expected 4)

**Comment by chaitjo** [comment]
1. No, we have not tested with dgl v0.4.3. Please, use the recomended version of dgl v0.4, according to the following file: https://github.com/graphdeeplearning/benchmarking-gnns/blob/master/environment_gpu.yml

2. If you are using conda/virtualenv, learning how to downgrade the package should be one google search away. Alternatively, uninstall and then re-install the correct version.

3. Superpixel datasets are prepared following the following repository: https://github.com/bknyaz/graph_attention_pool

**Comment by chaitjo** [comment]
You may refer to the following file on how we process the SLIC superpixels (which are obtained as described above: pt. 3): https://github.com/graphdeeplearning/benchmarking-gnns/blob/master/data/superpixels.py

**Comment by hust-nj** [comment]
OK, I know, thank you :)

**Comment by hust-nj** [comment]
Hello, now I want to make superpixel by myself, what is your superpixel max number `args.n_sp` in the following code? I see the origin nips paper _Understanding Attention and Generalization
in Graph Neural Networks_ it uses 75, what is your paper choosing of `n_sp`?

https://github.com/bknyaz/graph_attention_pool/blob/bdf97e04ec0a903f42113b2d8e1ac6ad8a1ad148/extract_superpixels.py#L39-L83

**Comment by vijaydwivedi75** [comment]
Hi @hust-nj, 

Also mentioned in the paper (Section 5.2/Figure 1 Caption), `n_sp` for MNIST is 75 and for CIFAR10 is 150.

**Comment by hust-nj** [comment]
Thank you!
I see.

**Comment by jermainewang** [comment]
Hi all, sorry for breaking your package. We have pushed a fix for the pickle compatibility issue in https://github.com/dmlc/dgl/pull/1507 . Once that is merged, please install with the latest nightly build version (using commands like `pip install --pre dgl`; see [here](https://www.dgl.ai/pages/start.html) for instructions) and everything should work again.

**Comment by vijaydwivedi75** [comment]
Thanks @jermainewang.
