### ISSUE TITLE
SBM_CLUSTER and SBM_PATTERN unable to unpack

### ISSUE THREAD

**Issue by Lavenderjiang** [graphdeeplearning/benchmarking-gnns#13]
Hi, I think the codes (or dataset, not sure) for loading node classification datasets SBM_CLUSTER and SBM_PATTERN are buggy. I got "too many values to unpack" error when I tried to reproduce the result for SBM. Below is the log

> (benchmark_gnn) -bash-4.2$ python main_SBMs_node_classification.py --dataset SBM_CLUSTER --gpu_id 0 --seed 41 --config 'configs/SBMs_node_clustering_MLP_CLUSTER.json'
> Using backend: pytorch
> cuda available with GPU: TITAN X (Pascal)
> [I] Loading dataset SBM_CLUSTER...
> Traceback (most recent call last):
>   File "main_SBMs_node_classification.py", line 409, in <module>
>     main()
>   File "main_SBMs_node_classification.py", line 307, in main
>     dataset = LoadData(DATASET_NAME)
>   File "/afs/ece.cmu.edu/usr/yaoj/Desktop/benchmarking-gnns/data/data.py", line 33, in LoadData
>     return SBMsDataset(DATASET_NAME)
>   File "/afs/ece.cmu.edu/usr/yaoj/Desktop/benchmarking-gnns/data/SBMs.py", line 132, in __init__
>     f = pickle.load(f)
>   File "/afs/ece.cmu.edu/usr/yaoj/anaconda3/envs/benchmark_gnn/lib/python3.7/site-packages/dgl/graph_index.py", line 53, in __setstate__
>     num_nodes, readonly, src, dst = state
> ValueError: too many values to unpack (expected 4)

**Comment by Lavenderjiang** [comment]
Oh! turns out that it's a problem with version of dgl-cuda10.0. I downgraded the package to 4.2 by running
`pip install dgl-cu100==0.4.2`
And it's good. 
Perhaps the [gpu environment file](https://github.com/graphdeeplearning/benchmarking-gnns/blob/master/environment_gpu.yml) can be updated to resolve this problem?

**Comment by chaitjo** [comment]
@Lavenderjiang Thanks for pointing this out. Indeed, our code seems incompatible with the latest DGL update, which came out rather recently.

**Comment by chaitjo** [comment]
@vijaydwivedi75 Let us fix the DGL version to 0.4.2 for now, and think of upgrading it later?
