### ISSUE TITLE
How to convert image data into graph structure data based on superpixel？

### ISSUE THREAD

**Issue by chenqz1998** [graphdeeplearning/benchmarking-gnns#18]
Hello~ I wanna add a new dataset. I saw that in MNIST(superpixel) data fold, there are only mnist_75sp_test.pkl and mnist_75sp_train.pkl. But I do not know how to convert my image data into such XXX.pkl. 
Thanks!

**Comment by vijaydwivedi75** [comment]
Hi @chenqz1998, thanks for your interest in this work.

We do mention in the paper the source for preparing the superpixels (generated using SLIC algorithm), see Section 5.2.

In case you missed, please refer to [this project](https://github.com/bknyaz/graph_attention_pool.) for code to convert your image data to superpixels.


Cheers!

**Comment by progs2002** [comment]
Hey, @vijaydwivedi75 the link is not working anymore do you happen to have a new link?
