### ISSUE TITLE
Why max pooling should be powerful than average pooling in Appendix E.2.

### ISSUE THREAD

**Issue by lihuiknight** [graphdeeplearning/benchmarking-gnns#20]
Dear Authors,

In[ Benchmarking Graph Neural Networks](https://arxiv.org/pdf/2003.00982.pdf), you said the max pooling should be more powerful than the average pooling (Appendix E.2). Why this statement is right? Does any theoretic guarantee or it's just empirical conclusion? 

Best,
Ken

**Comment by chaitjo** [comment]
Hi @lihuiknight, empirically, the GraphSage paper found that Maxpool aggregator was the post powerful. In our work, we started with a simple mean aggregator but will update to Maxpool soon. The performance isn't hugely different but Maxpool is slightly better.

In mean, the neighborhood features do not undergo any linear transformation before aggregation. In Maxpool, they undergo a linear transformation before aggregating as the element-wise max. We feel this operation gives more capacity to Maxpool style aggregators, thus the better performance.

**Comment by lihuiknight** [comment]
Thanks for your feedback.
