### ISSUE TITLE
Packet conflicts on Windows 10

### ISSUE THREAD

**Issue by gcorso** [graphdeeplearning/benchmarking-gnns#21]
I have tried installing the environment as specified in the guide, but I get a lot of packet conflicts when running `conda env create -f environment_cpu.yml` . Environment details: OS: Windows 10, no gpu. I don't get the same conflicts when running it on a Linux VM, any idea why?

**Comment by chaitjo** [comment]
I am not sure if we support Windows for development.. @vijaydwivedi75

**Comment by chaitjo** [comment]
I believe we do not support Windows/have not tested the code on Windows. I suggest using the Linux VM, instead.
