### ISSUE TITLE
Question about the num_atom_type and num_bond_type on zinc dataset

### ISSUE THREAD

**Issue by ihollywhy** [graphdeeplearning/benchmarking-gnns#23]
Hi, 

I use "data/molecules.py" to load the zinc dataset.
But I got confused when computing the num_atom_type and num_bond_type.

It is said that there are 28 different atom types and four bond types. However, the actual numbers I got are 21 and 3.

Does anyone know why?

```
{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20}
{1, 2, 3}
```

Here is my code:
```
    zinc_dataset = MoleculeDatasetDGL()
    node_set = set()
    edge_set = set()
    for data in zinc_dataset.train:
        g, label = data
        node_set = node_set.union( set(g.ndata['feat'].numpy()) )
        edge_set = edge_set.union( set(g.edata['feat'].numpy()) )
    print(node_set)
    print(edge_set)
```

**Comment by chaitjo** [comment]
Hi, thanks for pointing this out. Here is my understanding of what may be causing this:
- We firstly subb-sample the full ZINC dataset to get 12K samples (as we found this number to be good enough to statistically separate GNNs). Thus, there may be 7 rare atom types missing in our particular 12K samples, but the complete ZINC data will have all 28 atoms. You can actually prepare the complete dataset in our format without sampling, too.
- For the edge types, type 0 was used to represent 'no bond' between atoms (1, 2, 3 represent single, double and aromatic bonds). However, once we convert from dense adjacency matrices to DGL graphs, there is no need to create these type 0 edges. We can use true graph structure. 

Thanks for pointing this out, we will make a note of documenting this. I hope that clarifies the situation!
