### ISSUE TITLE
GatedGCN version

### ISSUE THREAD

**Issue by WangYibucea** [graphdeeplearning/benchmarking-gnns#24]
I am a newbie, is the GatedGCN in the layers the GatedGCN-E version?And What is their difference？

**Comment by chaitjo** [comment]
The paper will be updated to make the difference clear. 

To clarify, GatedGCN layer implements the exact node and edge update equations described in the current Appendix for the GatedGCN model. What we denote as GatedGCN-E is simply when we use the input edge features provided in a dataset to initialize the e_ij, i.e. the edge representations, for the GatedGCN model. 

Naturally, there are other ways to use edge features, too.

**Comment by WangYibucea** [comment]
Thanks for your expression.Expect your update. o(*￣▽￣*)ブ




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Chaitanya Joshi"<notifications@github.com&gt;; 
发送时间: 2020年6月9日(星期二) 下午2:48
收件人: "graphdeeplearning/benchmarking-gnns"<benchmarking-gnns@noreply.github.com&gt;; 
抄送: "Mr.Pro"<1207918198@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [graphdeeplearning/benchmarking-gnns] GatedGCN version (#24)





 
The paper will be updated to make the difference clear.
 
To clarify, GatedGCN layer implements the exact node and edge update equations described in the current Appendix for the GatedGCN model. What we denote as GatedGCN-E is simply when we use the input edge features provided in a dataset to initialize the e_ij, i.e. the edge representations, for the GatedGCN model.
 
Naturally, there are other ways to use edge features, too.
