### ISSUE TITLE
DiffPool Layer & Net

### ISSUE THREAD

**Issue by incenger** [graphdeeplearning/benchmarking-gnns#26]
The `version 2 update` commit removes the DiffPool layer and net implementation. What happens with this structure?

**Comment by vijaydwivedi75** [comment]
Hi @incenger, thanks for your question.

We had a major [update to the paper](https://arxiv.org/pdf/2003.00982v2.pdf) and we focus more comprehensively to different classes of GNNs. 

DiffPool is a hierarchical differentiable graph pooling mechanism, and the model can be built by using any GNN at each level of hierarchy. This falls in a line of work focused on generating hierarchical layer representations of graphs. We plan to dive in detail on pooling-based models later in future works.

For now, in case you want to access the code for DiffPool and other models for the earlier version of this work, please check [this branch](https://github.com/graphdeeplearning/benchmarking-gnns/tree/arXivV1).

Best,
Vijay

**Comment by incenger** [comment]
@vijaydwivedi75 Thank you :)
