### ISSUE TITLE
SBM_PATTERN data changed?

### ISSUE THREAD

**Issue by se-ok** [graphdeeplearning/benchmarking-gnns#28]
Hi, thank you for your wonderful work.
I have used the datasets ZINC, SBM_CLUSTER, SBM_PATTERN from the past February. Today, I found the paper is updated substantially and looked through the datasets.
It occurs to me that while ZINC, SBM_CLUSTER pkl file links are as they were but SBM_PATTERN link got changed. Is it safe to use the SBM_PATTERN pkl file from February still?
Or could you tell me what have changed since?

**Comment by vijaydwivedi75** [comment]
Hi @se-ok, thanks for your interest and the question.

The SBM_PATTERN dataset from the [first release](https://github.com/graphdeeplearning/benchmarking-gnns/tree/arXivV1) is good to use, given the characteristics you follow if you write detail on the dataset (refer Section 5.4 in [version 1 of arxiv paper](https://arxiv.org/pdf/2003.00982v1.pdf) for exact parameters for PATTERN generation.)

The parameter `q` and pattern size for the generation of PATTERN dataset has been changed in the current release to improve the dataset.(refer Appendix A.1 of the [updated arxiv paper](https://arxiv.org/pdf/2003.00982v2.pdf)) 

Therefore, it is safe to use any of the version, keeping in mind the corresponding detail of generation. If you compare your work with the tables in our new version, please use the current updated dataset.

Best,
Vijay

**Comment by se-ok** [comment]
Hi @vijaydwivedi75 , thank you so much for kindly pointing me to the relevant descriptions. Now I understand why the performances got a little lower than the previous version. I also thank you for the updated experiments including RingGNN and 3WLGNNs. Wish you the Best!
