### ISSUE TITLE
Discussion on leaderboards

### ISSUE THREAD

**Issue by chaitjo** [graphdeeplearning/benchmarking-gnns#29]
**An open discussion:** With the inclusion of leaderboards, would we like to keep updating them with new results as and when they hit arXiv? Should there be a protocol for leaderboard submissions and validating the results?

E.g. https://arxiv.org/abs/2006.07846, https://arxiv.org/abs/2004.05718

**Comment by vijaydwivedi75** [comment]
Created a PR #30 .

**Comment by chaitjo** [comment]
Feel free to re-open if someone has suggestions!
