### ISSUE TITLE
Preparing a dataset for node classification

### ISSUE THREAD

**Issue by saaay71** [graphdeeplearning/benchmarking-gnns#3]
Hi,
Thanks for sharing this framework. It was the missing tool and a big step for the gnn research.

If we have one graph and the task is to classify nodes, how should we prepare the dataset?
In other words, how to split one graph to train, val and test datasets for node classification using gnns?

Thanks,

**Comment by chaitjo** [comment]
Hi @saaay71, thanks for your interest. Indeed, we do provide examples of preparing node classification datasets on multiple graphs, e.g., PATTERN and CLUSTER datasets from the paper: https://github.com/graphdeeplearning/benchmarking-gnns/blob/master/data/SBMs.py

On the other hand, do you mean node classification on one (massive) graph, such as the popularly used Cora/Citeseer/Pubmed?

**Comment by saaay71** [comment]
Hey @chaitjo,
Yes, I meant "one (massive) graph" like Cora/Citeseer and Reddit post2post graph

**Comment by chaitjo** [comment]
Currently, these type of tasks aren't supported. The DGL library has nice tutorials on these tasks: https://docs.dgl.ai/en/0.4.x/tutorials/models/1_gnn/6_line_graph.html

**Comment by saaay71** [comment]
Thanks for the link and info.
