### ISSUE TITLE
f = pickle.load(f) ValueError: too many values to unpack (expected 4)

### ISSUE THREAD

**Issue by chezhihong1** [graphdeeplearning/benchmarking-gnns#31]
https://github.com/graphdeeplearning/benchmarking-gnns/blob/31a2e0e3673aa5463aec2c289a3b7d5c38e87203/data/superpixels.py#L270

This error occurred when I ran the following code on the command line:
`!python /content/main_superpixels_graph_classification.py --dataset MNIST --gpu_id 0 --config '/content/confi`gs/superpixels_graph_classification_GatedGCN_MNIST_100k.json' # for GPU
`
![image](https://user-images.githubusercontent.com/37236499/86429496-5329af80-bd22-11ea-8573-5d178943a97b.png)

When I change the code to the following, there is still the same error
self.train, self.val, self.test = pickle.load(f)

How to solve this error? thanks!

**Comment by chezhihong1** [comment]
The reason for this error is the version of DGL, When I downgraded DGL to 0.4.2, the problem was solved
`pip install dgl-cu101==0.4.2`

This bug appears in DGL 0.4.3 and has been solved in DGL 0.5x
![image](https://user-images.githubusercontent.com/37236499/86449789-3e154680-bd4b-11ea-9468-d90ac8e416fc.png)
you can't use pip to install 0.5x, so I chose to downgrade to 0.4.2

**Comment by chaitjo** [comment]
Indeed, if you install via the conda environment we provide, it will also fix the dgl version to 0.4.2 (which is what we used)..

**Comment by chezhihong1** [comment]
> Indeed, if you install via the conda environment we provide, it will also fix the dgl version to 0.4.2 (which is what we used)..

thanks
