### ISSUE TITLE
include Training and Inferencing speed, along with memory usage

### ISSUE THREAD

**Issue by deepseek** [graphdeeplearning/benchmarking-gnns#33]
including the Training and Inferencing speed, along with the Memory Usage is important

**Comment by chaitjo** [comment]
Hi, if you're requesting a feature, could you give an example/provide more information on your request?

**Comment by deepseek** [comment]
have a look at https://github.com/PaddlePaddle/PGL
they have speed (epoch time)

and you can include the ram usage

**Comment by XUHAN314** [comment]
In the training epoch, why use:
batch_scores = model.forward(batch_graphs, batch_x, batch_e, batch_snorm_n, batch_snorm_e)

not:
batch_scores = model(batch_graphs, batch_x, batch_e, batch_snorm_n, batch_snorm_e)

I am wondering if using forward function directly could cause some problems during the training.
