### ISSUE TITLE
Additional Mirror for Datasets

### ISSUE THREAD

**Issue by ZW-ZHANG** [graphdeeplearning/benchmarking-gnns#36]
Thanks for providing the benchmark!

As a Ph.D student working on GNNs in China, I'd like to ask you considering providing additional mirror for the datasets, e.g., on github or other websites, since dropbox may not be accessble for us. 

(Just to mention, similar problems have happend in other packages as well, e.g., see https://github.com/rusty1s/pytorch_geometric/issues/1116#issuecomment-612580946)

**Comment by chaitjo** [comment]
Hi @ZW-ZHANG, thanks for pointing this out. What would you suggest as an additional mirror?

**Comment by ZW-ZHANG** [comment]
Thanks for the response. I guess AWS should be fine, or Tencent/Alibaba/Baidu cloud (but I am not sure how well they are supported outside of China)

**Comment by vijaydwivedi75** [comment]
Hi @ZW-ZHANG, we shall be moving the datasets to DGL server (AWS) after we integrate update for the [DGL 0.5](https://github.com/graphdeeplearning/benchmarking-gnns/pull/38).
Thanks for your question.

**Comment by vijaydwivedi75** [comment]
Hi @ZW-ZHANG, you may find the repo [updated](https://github.com/graphdeeplearning/benchmarking-gnns#updates) which has new links for datasets hosted on DGL.

Ps. The new datasets work with the latest DGL/PyTorch. So please update your working environment as well.

**Comment by ZW-ZHANG** [comment]
That's good to know and I will try it out sometime. Thanks for your help.
