### ISSUE TITLE
Graph features

### ISSUE THREAD

**Issue by giacomolc** [graphdeeplearning/benchmarking-gnns#37]
Is it possible to add a graph feature (a vector for each graph) to be used togheter with the graph itself to predict the label, in the graph classification/ graph regression settings? If it is, how can I do so? I'm not very experienced with torch and tensorflow. Thank you in advance.

**Comment by vijaydwivedi75** [comment]
Hi @giacomolc, thanks for your question.

Yes, it can be done after you readout node representations to get the final graph feature vector. 

Please look at the comment in the below snippet from https://github.com/graphdeeplearning/benchmarking-gnns/blob/master/nets/molecules_graph_regression/gcn_net.py#L39
```
    def forward(self, g, h, e):
        h = self.embedding_h(h)
        h = self.in_feat_dropout(h)
        
        for conv in self.layers:
            h = conv(g, h)
        g.ndata['h'] = h
        
        if self.readout == "sum":
            hg = dgl.sum_nodes(g, 'h')
        elif self.readout == "max":
            hg = dgl.max_nodes(g, 'h')
        elif self.readout == "mean":
            hg = dgl.mean_nodes(g, 'h')
        else:
            hg = dgl.mean_nodes(g, 'h')  # default readout is mean nodes
            
        """
           hg is the graph representation
           Feature vector for graph can be added at this stage to hg
        """
        return self.MLP_layer(hg)
```

**Comment by chaitjo** [comment]
@giacomolc If you would like to use a graph-level feature, i.e. a pre-provided graph vector in addition to the graph feature vector that is readout from the GNN, the simplest approach in my mind would be to concatenate it with the `hg` variable in @vijaydwivedi75's example. You can look at the documentation of `torch.concat` for it. 

The concatenated feature from the GNN and from the input can then be passed to an MLP to classify the graph. Hope it helps!

**Comment by giacomolc** [comment]
I'm trying to concatenate to hg my features as said, but I'm having some problems with the MLP_layer in the following, since it expect a different dimention

**Comment by chaitjo** [comment]
You should increase the in dimension of the MLP_layer from `out_dim` to `out_dim+my_feat_dim` if you know the exact dimension of your custom graph level feature.
