### ISSUE TITLE
tar cannot extract zip file!

### ISSUE THREAD

**Issue by hust-nj** [graphdeeplearning/benchmarking-gnns#4]
Hi, when I run the following file
<https://github.com/graphdeeplearning/benchmarking-gnns/blob/master/data/superpixels/prepare_superpixels_MNIST.ipynb>

in line 
```python
if not os.path.isfile('superpixels.zip'):
    print('downloading..')
    !curl https://www.dropbox.com/s/y2qwa77a0fxem47/superpixels.zip?dl=1 -o superpixels.zip -J -L -k
    !tar -xvf superpixels.zip -C ../
else:
    print('File already downloaded')
```
it exists an error 

> tar: This does not look like a tar archive

Maybe we should change the command 
```python
!tar -xvf superpixels.zip -C ../
```
to 
```python
!unzip superpixels.zip -d ../
```

Thank you!

**Comment by vijaydwivedi75** [comment]
Hi @hust-nj, thanks for the interest in our work and pointing this out.

Although the `tar` command worked somehow, we've updated the respective files with `unzip` to work on most systems.

The updated notebook files, in the dataset preparation stage (eg. the notebook you mention), now use

```!unzip <dataset>.zip -d ../```

Closing the issue,
Thanks.
