### ISSUE TITLE
How to open atom_dict.pickle of ZINC dataset?

### ISSUE THREAD

**Issue by Nardien** [graphdeeplearning/benchmarking-gnns#42]
Hi. First of all, thank you for your great work for establishing a benchmark for GNN.

Now we try to visualize the data from ZINC dataset using rdkit.

However, we fail to find the proper dictionary of atom type for ZINC data.

We think that the file named atom_dict.pickle contains such contents, but we cannot open this via pickle because it causes the error as follows:

AttributeError: Can't get attribute 'Dictionary' on <module '__main__' from 'open_pickle.py'>

So, can you share the method for open atom_dict.pickle file or share the dictionary for ZINC atoms? Then it will be very grateful.

Thank you.

**Comment by chaitjo** [comment]
Hi @Nardien, thanks for your interest. I would suggest obtaining the full ZINC dataset via the TU Dortmund repository: https://chrsmrrs.github.io/datasets/docs/datasets/

Within the downloaded files, you can find detailed descriptions re. ZINC. We used this dataset based on pioneering work in molecule generation, You-etal, 2018; Ying-etal, 2019.

Here is the information you are looking for:
```
=== Description of the dataset === 

The node labels are atom types and the edge labels atom bond types.

Node labels:

'C': 0
'O': 1
'N': 2
'F': 3
'C H1': 4
'S': 5
'Cl': 6
'O -': 7
'N H1 +': 8
'Br': 9
'N H3 +': 10
'N H2 +': 11
'N +': 12
'N -': 13
'S -': 14
'I': 15
'P': 16
'O H1 +': 17
'N H1 -': 18
'O +': 19
'S +': 20
'P H1': 21
'P H2': 22
'C H2 -': 23
'P +': 24
'S H1 +': 25
'C H1 -': 26
'P H1 +': 27

Edge labels:

'SINGLE': 1
'DOUBLE': 2
'TRIPLE': 3
```

We will include this meta-information in a better way in the next version of our benchmark.
