### ISSUE TITLE
Now, I can't download the MNIST dataset. Could you please give me a new url for downloading?

### ISSUE THREAD

**Issue by jwwu666** [graphdeeplearning/benchmarking-gnns#43]

**Comment by vijaydwivedi75** [comment]
Hi @jwwu666, please use [this url](http://bit.ly/mnistpkl-dgl04) for MNIST pkl dataset download.

**Comment by vijaydwivedi75** [comment]
Hi @jwwu666, please find the new URL links for dataset download in the data/ directory.
I hope you will be able to download using the new links.

Ps. Update your environment using the new yml files as the repo and the datasets get updated to latest DGL 0.5.2.
