### ISSUE TITLE
graphsage parameters

### ISSUE THREAD

**Issue by giacomolc** [graphdeeplearning/benchmarking-gnns#44]
In graphsage at each layer each node updates its embedding with a fixed (S_i) number of neighbors. Is it possible in this framework to choose the S_i parameters for the 2 layers in graphsage? I don't see the possibility
Thank you anyway

**Comment by vijaydwivedi75** [comment]
Hi @giacomolc, you are right, we have not implemented the sampling strategy for graphsage here.
You may use DGL docs to implement just the neighborhood sampling part.
