### ISSUE TITLE
Node features for CLUSTER dataset

### ISSUE THREAD

**Issue by yueqiw** [graphdeeplearning/benchmarking-gnns#45]
Hi, thank you for providing a great benchmark!

I have a question about the CLUSTER dataset. As stated in the paper, the input attributes for all nodes are zero except for the 6 "seed" nodes which have one-hot input features [1,2,3,4,5,6]. Are these the only node attributes that are fed into the GNNs? I wonder if non-zero node attributes are used/needed for the non-seed nodes?

Thanks!

**Comment by vijaydwivedi75** [comment]
Hi @yueqiw,
Please find [this reference](https://github.com/graphdeeplearning/benchmarking-gnns/issues/9) to an earlier clarification on the same.
