### ISSUE TITLE
About adj matrix and g.edata['feat']

### ISSUE THREAD

**Issue by chenzhuer** [graphdeeplearning/benchmarking-gnns#5]
Hi~first I would like to appreciate all contributors for such an awesome job，thanks！
I’m not familiar with the module “dgl”，so I have some confusion about the code.
I think the adj matrix should participate in the operation，but i didn't find it  in the code.
Meanwhile， I'm not sure about the meaning of g.edata['feat']. For example, what does it stand for in SBM Datasets?
Thanks for your reply in advance.
Hope a nice day!

**Comment by vijaydwivedi75** [comment]
Hi @chenzhuer, thanks for your interest in this work.

When we prepare the DGL graphs, we use the following protocol, in general. The adjacency lists are used and not the dense adjacency matrix. Please refer to the doc [here](https://github.com/graphdeeplearning/benchmarking-gnns/blob/master/docs/04_add_dataset.md#22-save-your-data-in-dgl-format). For an example, please see any of the `<dataset>.py` files in [/data/](https://github.com/graphdeeplearning/benchmarking-gnns/tree/master/data) directory.

``` 
# Steps
# S1: initilize a dgl graph g = dgl.DGLGraph()
# S2: add nodes using g.add_nodes()
# S3: add edges using g.add_edges()
# S4: add node feat by assigning a torch tensor to g.ndata['feat'] 
# S5: add edge feat by assigning a torch tensor to g.edata['feat']
# S6: Append the dgl graph to self.graph_lists

# Repeat Steps S1 to S6 for 'n_samples' number of times
```

To know fundamentally how DGL uses graph nodes and edges, please follow these two resource pages on DGL Docs.

1.[https://docs.dgl.ai/api/python/graph.html#querying-graph-structure](https://docs.dgl.ai/api/python/graph.html#querying-graph-structure)
2.[https://docs.dgl.ai/tutorials/basics/2_basics.html#creating-a-graph](https://docs.dgl.ai/tutorials/basics/2_basics.html#creating-a-graph)

The adjacency matrix can still be queried using this method [here](https://docs.dgl.ai/generated/dgl.DGLGraph.adjacency_matrix.html#dgl.DGLGraph.adjacency_matrix).
```
dgl.DGLGraph.adjacency_matrix()
```

--

If you'd have seen the above links by now, you would learn that `g.ndata['feat']` is the tensor for the node features of all nodes in the graph. If `N` is the number of nodes and `F` is the dimension of a node feature vector, then `g.ndata['feat']` would be a `NxF` tensor. More details [here](https://docs.dgl.ai/tutorials/basics/2_basics.html#assigning-a-feature).

For SBM dataset preparation, please refer to Section 5.4 in the paper. Here is the summary of all datasets used. 
![Capture](https://user-images.githubusercontent.com/17483519/76589908-a1723300-6526-11ea-9f98-ebbad03c410e.JPG)


Hope this helps.
Thanks!
