### ISSUE TITLE
Enhancement, adding a model

### ISSUE THREAD

**Issue by Axeln78** [graphdeeplearning/benchmarking-gnns#51]
Hi! 

I have a fork of the repo where I made the corresponding changes to add the ChebNet. Would you be interested to integrate it if I make a pull request for that or do you prefer keeping the repo as your own code production for the time being?

Best,
Axel

**Comment by vijaydwivedi75** [comment]
Hi @Axeln78,

Thank you for the ChebNet experiments.

Please refer to the instructions [here](https://github.com/graphdeeplearning/benchmarking-gnns/blob/master/docs/07_contribute_leaderboards.md#adding-new-gnn-codes-to-the-benchmark-repo) on the contributions.
We keep the current repo and not add new models, in order for the project to be minimal for ease of use. However, contributions to leaderboards are welcome!

Cheers,
Vijay
