### ISSUE TITLE
GCNLayer reduce function

### ISSUE THREAD

**Issue by cyh1112** [graphdeeplearning/benchmarking-gnns#52]
why implement the reduce function of GCNLayer use a custom function, not fn.mean?

layers/gcn_layer.py line 18~20
```
def reduce(nodes):
    accum = torch.mean(nodes.mailbox['m'], 1)
    return {'h': accum}
```

I replaced to fn.mean and got a great speedup, is there any bug in fn.mean?

**Comment by yzh119** [comment]
Hi, I'm from DGL team and I think you should use `fn.mean`, the author might not be aware of `fn.mean` when the code was written. Using built-in functions could accelerate your code in most cases.

**Comment by cyh1112** [comment]
> Hi, I'm from DGL team and I think you should use `fn.mean`, the author might not be aware of `fn.mean` when the code was written. Using built-in functions could accelerate your code in most cases.

Hi, thanks for your reply
I tested the function `fn.mean` and got the same result. thanks again, DGL is a great tools. lol
