### ISSUE TITLE
Question about 'z' variable 

### ISSUE THREAD

**Issue by DevinKreuzer** [graphdeeplearning/benchmarking-gnns#58]
Hi! Thanks for this great work!

I was just curious as to what it he 'z' variable in line 59 of graph_transformer_layer.py? I cannot seem to find this variable in the paper. It seems to be dividing the output from the multihead attention. Is there a specific reason as to why this was necessary?

Thanks :)

**Comment by chaitjo** [comment]
Could you point to the specific file's URL?

**Comment by DevinKreuzer** [comment]
https://github.com/graphdeeplearning/graphtransformer/blob/main/layers/graph_transformer_layer.py

Line 59. I can't seem to figure out which variable this is? Would appreciate a pointer :)

Thanks!

**Comment by chaitjo** [comment]
You would probably be better served by opening the issue in the graphtransformer repository. (And it would help out other users, too!)
