### ISSUE TITLE
Always use gpu0

### ISSUE THREAD

**Issue by hust-nj** [graphdeeplearning/benchmarking-gnns#6]
Hi, when I ran your script <https://github.com/graphdeeplearning/benchmarking-gnns/blob/master/script_one_code_to_rull_them_all.sh>
I found all the processes were running on gpu0.
Your code of choosing gpu is setting environment variables in code.
```python
def gpu_setup(use_gpu, gpu_id):
    os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"
    os.environ["CUDA_VISIBLE_DEVICES"] = str(gpu_id)  

    if torch.cuda.is_available() and use_gpu:
        print('cuda available with GPU:',torch.cuda.get_device_name(0))
        device = torch.device("cuda")
    else:
        print('cuda not available')
        device = torch.device("cpu")
    return device
```
But In my machine with 8 gpus, it caused the same issue as <https://discuss.pytorch.org/t/why-setting-cuda-visible-devices-within-the-code-doesn-t-work/31826>
**All processes run only on gpu:0**.

And I found other people said that setting variables outside of the code or before importing something associated with gpu would be better.
I wonder that **if you have the same issue or just everything runs normally?**
I think using the methods in <https://pytorch.org/docs/master/notes/cuda.html> may be better and more compatible.
Thanks for your answer!

**Comment by hust-nj** [comment]
What's more:
I test if I change your `gpu_setup` function to 
```python
def gpu_setup(use_gpu, gpu_id):
    if torch.cuda.is_available() and use_gpu:
        device = torch.device(f'cuda:{gpu_id}')
        print('cuda available with GPU:',torch.cuda.get_device_name(gpu_id))
    else:
        print('cuda not available')
        device = torch.device("cpu")
    return device
```
Then It's ok to choose which gpu to use.

**Comment by vijaydwivedi75** [comment]
Hi @hust-nj, thank you for your interest in this work.

Yes, we use the code in `gpu_setup()` function to select the GPU to train on, and it runs well in our systems. The specified gpu is chosen every time and we have no issues, like you faced. We also ran on multiple GPU servers and things were working as expected.

--
I see that you modify the `gpu_setup()` to solve the problem for you. If it works fine, please go ahead. I will try to figure if we need to make the change for running on all kinds of systems.

Thanks.
