### ISSUE TITLE
Question about converting super-pixel image as a graph

### ISSUE THREAD

**Issue by StrongWeiUMN** [graphdeeplearning/benchmarking-gnns#60]
I am trying to read **superpixels_visualization_mnist.ipynb** and feel confuse about the function **compute_edges_list(A, kth=8+1)**:

`knns = np.argpartition(A, new_kth-1, axis=-1)[:, new_kth:-1]`

We ignore the last column in that case. I think it is better to use 

`knns = np.argpartition(A, new_kth, axis=-1)[:, new_kth+1:]`.

Let me know if I am wrong. Thank you very much!

**Comment by chaitjo** [comment]
Hi @StrongWeiUMN, thanks for your interest! Here is more detail on the k-NN computation in super-pixel graphs: #22 #17 

Hope it helps.
