### ISSUE TITLE
Where is the implementation of `Graph Size Normalization`?

### ISSUE THREAD

**Issue by Dinxin** [graphdeeplearning/benchmarking-gnns#62]
This paper claimed that the introduction of so-called `graph size normalization` can boost performance in various graph machine learning tasks. But, I can't find the implementation of this simple and effective normalization. Therefore, could anyone point out the exact place of this implementation?

**Comment by vijaydwivedi75** [comment]
Hi @Dinxin,

It is implemented in an [earlier version of the repo](https://github.com/graphdeeplearning/benchmarking-gnns/tree/arXivV1) in every `<data>.py` file in the `data/` directory.

For instance for ZINC: https://github.com/graphdeeplearning/benchmarking-gnns/blob/a17fdf1b1d758fc65d5eeaf3726f5efa747a4081/data/molecules.py#L165-L167
The values thus calculated are used at a GNN layer as: https://github.com/graphdeeplearning/benchmarking-gnns/blob/a17fdf1b1d758fc65d5eeaf3726f5efa747a4081/layers/gcn_layer.py#L58-L59
