### ISSUE TITLE
 The ZINC dataset can't be download.

### ISSUE THREAD

**Issue by xkxxfyf** [graphdeeplearning/benchmarking-gnns#65]
The url https://www.dropbox.com/s/feo9qle74kg48gy/molecules.zip seems to have failed. Could you please give me a new url for downloading?

**Comment by chaitjo** [comment]
Hi @xkxxfyf, you can alternatively download the dataset via DGL directly or from TUDatasets: https://chrsmrrs.github.io/datasets/
