### ISSUE TITLE
Explanation of Node Classification Tasks

### ISSUE THREAD

**Issue by AndyJZhao** [graphdeeplearning/benchmarking-gnns#66]
Hi,
I really appreciate your great work. However, I find it very difficult to understand what the SBM datasets of node classification in this repo and the corresponding paper "Benchmarking Graph Neural Networks" is doing. It would be very kind of you to enlight me on the following questions:

Q1. What is the key drawback of using traditional node classification datasets, where node properties are predicted on a single graph only. The paper states that Cora and Citeseer are not big enough. However, are there any other advantages of using proposed SBM datasets against OGBN-Arxiv (with 169k nodes).

Q2. Is there any detailed description regarding the node classification datasets other than the description in the paper (A.1)? I tried my best to understand the description but I couldn't understand the meaning of it. For example, how to define patterns? Why 100 patterns are treated as the same label? 

Looking forward to your reply.

**Comment by vijaydwivedi75** [comment]
Hi @Andy-Border,

Thanks for your queries on node classification datasets. 

You may refer few earlier discussions https://github.com/graphdeeplearning/benchmarking-gnns/issues/39, https://github.com/graphdeeplearning/benchmarking-gnns/issues/9 in case relevant.
For Q1. Other datasets such as ogbn-arxiv can be used are they are real datasets representing a citation network and are larger than Cora/Citeseer. For SBMs, these are synthetically generated and hence is clean if you're interested to study some models, eg. whether they're able to predict the properties in the datasets.
For Q2. I believe the appendix contains the information and as mentioned, these are synthetically created with certain parameters controlling connectivity.

Best,
Vijay
