### ISSUE TITLE
HELP: A question regarding the implementation of the GatedGCN layer

### ISSUE THREAD

**Issue by ChangyWen** [graphdeeplearning/benchmarking-gnns#67]
# A question regarding the implementation of the GatedGCN layer

## Question: Is the implementation of the GatedGCN layer consistent with the one described in the paper (i.e., Equations (24)-(26), or equivalently, Equations (58)-(60))?    
Please note that I am new to GCN. I would deeply appreciate it if anyone could help on my issue!!!

* Please see a part of the implementation of the GatedGCN layer in [`gated_gcn_layer.py`](https://github.com/graphdeeplearning/benchmarking-gnns/blob/master/layers/gated_gcn_layer.py) below.
https://github.com/graphdeeplearning/benchmarking-gnns/blob/62c32cc052f2effc4455493b941859e7ccb7025d/layers/gated_gcn_layer.py#L35-L72

* Please see the description of the GatedGCN layer in the [paper](https://arxiv.org/pdf/2003.00982.pdf) below.
<img width="1312" alt="paper-version" src="https://user-images.githubusercontent.com/34892944/131152185-c2a0d5da-bdf7-42bf-abdd-a99bb65e9dcf.png">

* I have looked into the implementation of GatedGCN layer in this repo, and compared it with the one described in the paper. I don't really think they are consistent. Instead, I think the implementation tally with the version shown below. Please correct me if I am wrong. Thanks!!! 
<img width="1427" alt="Screenshot 2021-08-27 at 23 48 44" src="https://user-images.githubusercontent.com/34892944/131154439-682229d8-2c12-4c1c-a157-4823d93f4a42.png">

* For the convenience of discussion, please find below the tex of the aforementioned Equations (1)-(4).
```latex
\usepackage{amsthm}
\usepackage{mathtools}
\newcommand{\thickhat}[1]{\mathbf{\hat{\text{$#1$}}}}
\newcommand{\thicktilde}[1]{\mathbf{\tilde{\text{$#1$}}}}

% Equation (1)
\begin{equation}
    h_i^{l+1} = h_i^l + \text{ReLU}\left(\text{BN}\left(U^l h_i^l + \sum_{j\in \mathcal{N}_i}\thicktilde{e}_{ij}^{l+1} \odot V^l h_j^l\right)\right),
\end{equation}

% Equation (2)
\begin{equation}
    e^{l+1}_{ij} = e^{l}_{ij} + \text{ReLU}\left(\text{BN}\left(\thickhat{e}^{l+1}_{ij}\right)\right),
\end{equation}

% Equation (3)
\begin{equation}
    \thicktilde{e}^{l+1}_{ij} = \frac{\sigma(\thickhat{e}^{l+1}_{ij})}{\sum_{j' \in \mathcal{N}_i} \sigma(\thickhat{e}^{l+1}_{ij'}) + \epsilon},
\end{equation}

% Equation (4)
\begin{equation}
    \thickhat{e}^{l+1}_{ij} = A^l h_i^l + B^l h_j^l + C^l e^l_{ij}.
\end{equation}
```

**Comment by vijaydwivedi75** [comment]
Hi @ChangyWen,
Thanks for your question. 
Eqns 1-4 (that you mention) represent (correctly) the equations of the GatedGCN layer implemented in the code.
Though in principle and practice, both can be equivalent.
