### ISSUE TITLE
An issue in Reproducibility

### ISSUE THREAD

**Issue by 95tlsdud** [graphdeeplearning/benchmarking-gnns#74]
Hi,

I'm trying to run the code, but have an issue in section 3 Reproducibility.

if notebook_mode == True:
    
    #MODEL_NAME = '3WLGNN'
    #MODEL_NAME = 'RingGNN'
    MODEL_NAME = 'GatedGCN'
    #MODEL_NAME = 'MoNet'
    #MODEL_NAME = 'GCN'
    # MODEL_NAME = 'GAT'
    # MODEL_NAME = 'GraphSage'
    # MODEL_NAME = 'DiffPool'
    # MODEL_NAME = 'MLP'
    # MODEL_NAME = 'GIN'

    DATASET_NAME = 'ZINC'

    out_dir = 'out/molecules_graph_regression/'
    root_log_dir = out_dir + 'logs/' + MODEL_NAME + "_" + DATASET_NAME + "_" + time.strftime('%Hh%Mm%Ss_on_%b_%d_%Y')
    root_ckpt_dir = out_dir + 'checkpoints/' + MODEL_NAME + "_" + DATASET_NAME + "_" + time.strftime('%Hh%Mm%Ss_on_%b_%d_%Y')

    print("[I] Loading data (notebook) ...")
    dataset = LoadData(DATASET_NAME)
    trainset, valset, testset = dataset.train, dataset.val, dataset.test
    print("[I] Finished loading.")

However, I've got this error message:
_ModuleNotFoundError: No module named 'dgl.graph'._

So, I've tried to install dgl but still have a problem. So could you help me to figure out this problem, please?

Many thanks!

**Comment by chaitjo** [comment]
Thanks for your interest @95tlsdud; what version of Python/PyTorch/DGL are you using?

It is possible that there are breaking changes in the latest version of DGL. (The last supported version of DGL for benchmarking-gnns was v0.5.)

**Comment by 95tlsdud** [comment]
@chaitjo Thank you for answering this question! 

When I check my versions, 
Python 3.9.7
PyTorch 1.11.0
DGL 0.6.1.

So, I also tried to downgrade DGL version to 0.5 but I am afraid that I couldn't find the way to downgrade it. Do you have any suggestions to solve this problem, please?

**Comment by chaitjo** [comment]
You will have to go to the release notes of DGL v0.6.1, and see what the breaking changes are since v0.5.

E.g. it is possible that they have deprecated or renamed dgl.graph...
