### ISSUE TITLE
Install in different environment

### ISSUE THREAD

**Issue by Syzseisus** [graphdeeplearning/benchmarking-gnns#75]
Hi,
Could I reproduce in the environment which has:
`nvcc -V`: 
> Cuda compilation tools, release 11.2, V11.2.152
> Build cuda_11.2.r11.2/compiler.29618528_0

`lsb_release -a`:
> No LSB modules are available.
> Distributor ID: Ubuntu
> Description: Ubuntu 20.04.2 LTS
> Release: 20.04
> Codename: focal

with best regard,

**Comment by chaitjo** [comment]
You would have to ensure that you install the correct versions of the required packages, e.g. pytorch, dgl, etc. However, there may be differences in exact performance metrics across different hardware and cuda versions.
