### ISSUE TITLE
WARNING:root:NaN or Inf found in input tensor.

### ISSUE THREAD

**Issue by UnBuen** [graphdeeplearning/benchmarking-gnns#76]
Hello,
When I run _python main_superpixels_graph_classification.py --config 'configs/superpixels_graph_classification_GraphSage_CIFAR10_100k.json',
it shows that
![image](https://user-images.githubusercontent.com/37174252/168772169-c26e9d5e-9dde-4aa9-80f3-deda1c3c1c58.png)

but when i train with other networks such as gcn mlp on cifar, everything is ok.
I try to reduce learning rate, but also don't work on GraphSage net.

**Comment by vijaydwivedi75** [comment]
Hi @UnBuen, I tried to reproduce your error. But the experiment you mention runs well at my end.

![image](https://user-images.githubusercontent.com/17483519/168968262-b4becffc-23d8-462d-bce6-273267efacd9.png)
